// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/goto/raccoon/cache"
	mock "github.com/stretchr/testify/mock"
)

// NewDuplicateChecker creates a new instance of DuplicateChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDuplicateChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *DuplicateChecker {
	mock := &DuplicateChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DuplicateChecker is an autogenerated mock type for the DuplicateChecker type
type DuplicateChecker struct {
	mock.Mock
}

type DuplicateChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *DuplicateChecker) EXPECT() *DuplicateChecker_Expecter {
	return &DuplicateChecker_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type DuplicateChecker
func (_mock *DuplicateChecker) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DuplicateChecker_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DuplicateChecker_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DuplicateChecker_Expecter) Close() *DuplicateChecker_Close_Call {
	return &DuplicateChecker_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DuplicateChecker_Close_Call) Run(run func()) *DuplicateChecker_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DuplicateChecker_Close_Call) Return(err error) *DuplicateChecker_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DuplicateChecker_Close_Call) RunAndReturn(run func() error) *DuplicateChecker_Close_Call {
	_c.Call.Return(run)
	return _c
}

// IsDuplicate provides a mock function for the type DuplicateChecker
func (_mock *DuplicateChecker) IsDuplicate(ctx context.Context, event cache.EventMetadata) (bool, error) {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for IsDuplicate")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cache.EventMetadata) (bool, error)); ok {
		return returnFunc(ctx, event)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cache.EventMetadata) bool); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cache.EventMetadata) error); ok {
		r1 = returnFunc(ctx, event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DuplicateChecker_IsDuplicate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDuplicate'
type DuplicateChecker_IsDuplicate_Call struct {
	*mock.Call
}

// IsDuplicate is a helper method to define mock.On call
//   - ctx context.Context
//   - event cache.EventMetadata
func (_e *DuplicateChecker_Expecter) IsDuplicate(ctx interface{}, event interface{}) *DuplicateChecker_IsDuplicate_Call {
	return &DuplicateChecker_IsDuplicate_Call{Call: _e.mock.On("IsDuplicate", ctx, event)}
}

func (_c *DuplicateChecker_IsDuplicate_Call) Run(run func(ctx context.Context, event cache.EventMetadata)) *DuplicateChecker_IsDuplicate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cache.EventMetadata
		if args[1] != nil {
			arg1 = args[1].(cache.EventMetadata)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DuplicateChecker_IsDuplicate_Call) Return(b bool, err error) *DuplicateChecker_IsDuplicate_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *DuplicateChecker_IsDuplicate_Call) RunAndReturn(run func(ctx context.Context, event cache.EventMetadata) (bool, error)) *DuplicateChecker_IsDuplicate_Call {
	_c.Call.Return(run)
	return _c
}
