// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// NewStencilClientMock creates a new instance of StencilClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStencilClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StencilClientMock {
	mock := &StencilClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StencilClientMock is an autogenerated mock type for the Client type
type StencilClientMock struct {
	mock.Mock
}

type StencilClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StencilClientMock) EXPECT() *StencilClientMock_Expecter {
	return &StencilClientMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type StencilClientMock
func (_mock *StencilClientMock) Close() {
	_mock.Called()
	return
}

// StencilClientMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type StencilClientMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *StencilClientMock_Expecter) Close() *StencilClientMock_Close_Call {
	return &StencilClientMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *StencilClientMock_Close_Call) Run(run func()) *StencilClientMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StencilClientMock_Close_Call) Return() *StencilClientMock_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *StencilClientMock_Close_Call) RunAndReturn(run func()) *StencilClientMock_Close_Call {
	_c.Run(run)
	return _c
}

// GetDescriptor provides a mock function for the type StencilClientMock
func (_mock *StencilClientMock) GetDescriptor(s string) (protoreflect.MessageDescriptor, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetDescriptor")
	}

	var r0 protoreflect.MessageDescriptor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (protoreflect.MessageDescriptor, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) protoreflect.MessageDescriptor); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(protoreflect.MessageDescriptor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StencilClientMock_GetDescriptor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDescriptor'
type StencilClientMock_GetDescriptor_Call struct {
	*mock.Call
}

// GetDescriptor is a helper method to define mock.On call
//   - s string
func (_e *StencilClientMock_Expecter) GetDescriptor(s interface{}) *StencilClientMock_GetDescriptor_Call {
	return &StencilClientMock_GetDescriptor_Call{Call: _e.mock.On("GetDescriptor", s)}
}

func (_c *StencilClientMock_GetDescriptor_Call) Run(run func(s string)) *StencilClientMock_GetDescriptor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StencilClientMock_GetDescriptor_Call) Return(messageDescriptor protoreflect.MessageDescriptor, err error) *StencilClientMock_GetDescriptor_Call {
	_c.Call.Return(messageDescriptor, err)
	return _c
}

func (_c *StencilClientMock_GetDescriptor_Call) RunAndReturn(run func(s string) (protoreflect.MessageDescriptor, error)) *StencilClientMock_GetDescriptor_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type StencilClientMock
func (_mock *StencilClientMock) Parse(s string, bytes []byte) (protoreflect.ProtoMessage, error) {
	ret := _mock.Called(s, bytes)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 protoreflect.ProtoMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) (protoreflect.ProtoMessage, error)); ok {
		return returnFunc(s, bytes)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) protoreflect.ProtoMessage); ok {
		r0 = returnFunc(s, bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(protoreflect.ProtoMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(s, bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StencilClientMock_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type StencilClientMock_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - s string
//   - bytes []byte
func (_e *StencilClientMock_Expecter) Parse(s interface{}, bytes interface{}) *StencilClientMock_Parse_Call {
	return &StencilClientMock_Parse_Call{Call: _e.mock.On("Parse", s, bytes)}
}

func (_c *StencilClientMock_Parse_Call) Run(run func(s string, bytes []byte)) *StencilClientMock_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StencilClientMock_Parse_Call) Return(protoMessage protoreflect.ProtoMessage, err error) *StencilClientMock_Parse_Call {
	_c.Call.Return(protoMessage, err)
	return _c
}

func (_c *StencilClientMock_Parse_Call) RunAndReturn(run func(s string, bytes []byte) (protoreflect.ProtoMessage, error)) *StencilClientMock_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type StencilClientMock
func (_mock *StencilClientMock) Refresh() {
	_mock.Called()
	return
}

// StencilClientMock_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type StencilClientMock_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
func (_e *StencilClientMock_Expecter) Refresh() *StencilClientMock_Refresh_Call {
	return &StencilClientMock_Refresh_Call{Call: _e.mock.On("Refresh")}
}

func (_c *StencilClientMock_Refresh_Call) Run(run func()) *StencilClientMock_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StencilClientMock_Refresh_Call) Return() *StencilClientMock_Refresh_Call {
	_c.Call.Return()
	return _c
}

func (_c *StencilClientMock_Refresh_Call) RunAndReturn(run func()) *StencilClientMock_Refresh_Call {
	_c.Run(run)
	return _c
}

// Serialize provides a mock function for the type StencilClientMock
func (_mock *StencilClientMock) Serialize(s string, ifaceVal interface{}) ([]byte, error) {
	ret := _mock.Called(s, ifaceVal)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}) ([]byte, error)); ok {
		return returnFunc(s, ifaceVal)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}) []byte); ok {
		r0 = returnFunc(s, ifaceVal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = returnFunc(s, ifaceVal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StencilClientMock_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type StencilClientMock_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
//   - s string
//   - ifaceVal interface{}
func (_e *StencilClientMock_Expecter) Serialize(s interface{}, ifaceVal interface{}) *StencilClientMock_Serialize_Call {
	return &StencilClientMock_Serialize_Call{Call: _e.mock.On("Serialize", s, ifaceVal)}
}

func (_c *StencilClientMock_Serialize_Call) Run(run func(s string, ifaceVal interface{})) *StencilClientMock_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StencilClientMock_Serialize_Call) Return(bytes []byte, err error) *StencilClientMock_Serialize_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *StencilClientMock_Serialize_Call) RunAndReturn(run func(s string, ifaceVal interface{}) ([]byte, error)) *StencilClientMock_Serialize_Call {
	_c.Call.Return(run)
	return _c
}
