// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"buf.build/gen/go/gotocompany/proton/protocolbuffers/go/gotocompany/raccoon/v1beta1"
	mock "github.com/stretchr/testify/mock"
)

// NewDedupService creates a new instance of DedupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDedupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DedupService {
	mock := &DedupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DedupService is an autogenerated mock type for the DedupService type
type DedupService struct {
	mock.Mock
}

type DedupService_Expecter struct {
	mock *mock.Mock
}

func (_m *DedupService) EXPECT() *DedupService_Expecter {
	return &DedupService_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type DedupService
func (_mock *DedupService) Apply(events []*raccoonv1beta1.Event, connGroup string) []*raccoonv1beta1.Event {
	ret := _mock.Called(events, connGroup)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 []*raccoonv1beta1.Event
	if returnFunc, ok := ret.Get(0).(func([]*raccoonv1beta1.Event, string) []*raccoonv1beta1.Event); ok {
		r0 = returnFunc(events, connGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*raccoonv1beta1.Event)
		}
	}
	return r0
}

// DedupService_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type DedupService_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - events []*raccoonv1beta1.Event
//   - connGroup string
func (_e *DedupService_Expecter) Apply(events interface{}, connGroup interface{}) *DedupService_Apply_Call {
	return &DedupService_Apply_Call{Call: _e.mock.On("Apply", events, connGroup)}
}

func (_c *DedupService_Apply_Call) Run(run func(events []*raccoonv1beta1.Event, connGroup string)) *DedupService_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*raccoonv1beta1.Event
		if args[0] != nil {
			arg0 = args[0].([]*raccoonv1beta1.Event)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DedupService_Apply_Call) Return(events1 []*raccoonv1beta1.Event) *DedupService_Apply_Call {
	_c.Call.Return(events1)
	return _c
}

func (_c *DedupService_Apply_Call) RunAndReturn(run func(events []*raccoonv1beta1.Event, connGroup string) []*raccoonv1beta1.Event) *DedupService_Apply_Call {
	_c.Call.Return(run)
	return _c
}
