// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/goto/raccoon/ingestionrule/action/dedup/cache"
	mock "github.com/stretchr/testify/mock"
)

// NewDuplicateChecker creates a new instance of DuplicateChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDuplicateChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *DuplicateChecker {
	mock := &DuplicateChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DuplicateChecker is an autogenerated mock type for the DuplicateChecker type
type DuplicateChecker struct {
	mock.Mock
}

type DuplicateChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *DuplicateChecker) EXPECT() *DuplicateChecker_Expecter {
	return &DuplicateChecker_Expecter{mock: &_m.Mock}
}

// AreDuplicates provides a mock function for the type DuplicateChecker
func (_mock *DuplicateChecker) AreDuplicates(ctx context.Context, events []cache.EventMetadata, ttl time.Duration) ([]bool, error) {
	ret := _mock.Called(ctx, events, ttl)

	if len(ret) == 0 {
		panic("no return value specified for AreDuplicates")
	}

	var r0 []bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []cache.EventMetadata, time.Duration) ([]bool, error)); ok {
		return returnFunc(ctx, events, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []cache.EventMetadata, time.Duration) []bool); ok {
		r0 = returnFunc(ctx, events, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []cache.EventMetadata, time.Duration) error); ok {
		r1 = returnFunc(ctx, events, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DuplicateChecker_AreDuplicates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AreDuplicates'
type DuplicateChecker_AreDuplicates_Call struct {
	*mock.Call
}

// AreDuplicates is a helper method to define mock.On call
//   - ctx context.Context
//   - events []cache.EventMetadata
//   - ttl time.Duration
func (_e *DuplicateChecker_Expecter) AreDuplicates(ctx interface{}, events interface{}, ttl interface{}) *DuplicateChecker_AreDuplicates_Call {
	return &DuplicateChecker_AreDuplicates_Call{Call: _e.mock.On("AreDuplicates", ctx, events, ttl)}
}

func (_c *DuplicateChecker_AreDuplicates_Call) Run(run func(ctx context.Context, events []cache.EventMetadata, ttl time.Duration)) *DuplicateChecker_AreDuplicates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []cache.EventMetadata
		if args[1] != nil {
			arg1 = args[1].([]cache.EventMetadata)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DuplicateChecker_AreDuplicates_Call) Return(bools []bool, err error) *DuplicateChecker_AreDuplicates_Call {
	_c.Call.Return(bools, err)
	return _c
}

func (_c *DuplicateChecker_AreDuplicates_Call) RunAndReturn(run func(ctx context.Context, events []cache.EventMetadata, ttl time.Duration) ([]bool, error)) *DuplicateChecker_AreDuplicates_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type DuplicateChecker
func (_mock *DuplicateChecker) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DuplicateChecker_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DuplicateChecker_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DuplicateChecker_Expecter) Close() *DuplicateChecker_Close_Call {
	return &DuplicateChecker_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DuplicateChecker_Close_Call) Run(run func()) *DuplicateChecker_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DuplicateChecker_Close_Call) Return(err error) *DuplicateChecker_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DuplicateChecker_Close_Call) RunAndReturn(run func() error) *DuplicateChecker_Close_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function for the type DuplicateChecker
func (_mock *DuplicateChecker) HealthCheck() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DuplicateChecker_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type DuplicateChecker_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
func (_e *DuplicateChecker_Expecter) HealthCheck() *DuplicateChecker_HealthCheck_Call {
	return &DuplicateChecker_HealthCheck_Call{Call: _e.mock.On("HealthCheck")}
}

func (_c *DuplicateChecker_HealthCheck_Call) Run(run func()) *DuplicateChecker_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DuplicateChecker_HealthCheck_Call) Return(err error) *DuplicateChecker_HealthCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DuplicateChecker_HealthCheck_Call) RunAndReturn(run func() error) *DuplicateChecker_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}
