// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/goto/raccoon/config"
	"github.com/goto/raccoon/ingestionrule/action/eval"
	"github.com/goto/raccoon/model"
	mock "github.com/stretchr/testify/mock"
)

// NewEvaluator creates a new instance of Evaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Evaluator {
	mock := &Evaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Evaluator is an autogenerated mock type for the Evaluator type
type Evaluator struct {
	mock.Mock
}

type Evaluator_Expecter struct {
	mock *mock.Mock
}

func (_m *Evaluator) EXPECT() *Evaluator_Expecter {
	return &Evaluator_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function for the type Evaluator
func (_mock *Evaluator) Evaluate(meta model.EventMetadata, rules map[string]eval.Condition) (bool, bool) {
	ret := _mock.Called(meta, rules)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 bool
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(model.EventMetadata, map[string]eval.Condition) (bool, bool)); ok {
		return returnFunc(meta, rules)
	}
	if returnFunc, ok := ret.Get(0).(func(model.EventMetadata, map[string]eval.Condition) bool); ok {
		r0 = returnFunc(meta, rules)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(model.EventMetadata, map[string]eval.Condition) bool); ok {
		r1 = returnFunc(meta, rules)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Evaluator_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type Evaluator_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - meta model.EventMetadata
//   - rules map[string]eval.Condition
func (_e *Evaluator_Expecter) Evaluate(meta interface{}, rules interface{}) *Evaluator_Evaluate_Call {
	return &Evaluator_Evaluate_Call{Call: _e.mock.On("Evaluate", meta, rules)}
}

func (_c *Evaluator_Evaluate_Call) Run(run func(meta model.EventMetadata, rules map[string]eval.Condition)) *Evaluator_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.EventMetadata
		if args[0] != nil {
			arg0 = args[0].(model.EventMetadata)
		}
		var arg1 map[string]eval.Condition
		if args[1] != nil {
			arg1 = args[1].(map[string]eval.Condition)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Evaluator_Evaluate_Call) Return(result bool, found bool) *Evaluator_Evaluate_Call {
	_c.Call.Return(result, found)
	return _c
}

func (_c *Evaluator_Evaluate_Call) RunAndReturn(run func(meta model.EventMetadata, rules map[string]eval.Condition) (bool, bool)) *Evaluator_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// Resource provides a mock function for the type Evaluator
func (_mock *Evaluator) Resource() config.PolicyResourceType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Resource")
	}

	var r0 config.PolicyResourceType
	if returnFunc, ok := ret.Get(0).(func() config.PolicyResourceType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.PolicyResourceType)
	}
	return r0
}

// Evaluator_Resource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resource'
type Evaluator_Resource_Call struct {
	*mock.Call
}

// Resource is a helper method to define mock.On call
func (_e *Evaluator_Expecter) Resource() *Evaluator_Resource_Call {
	return &Evaluator_Resource_Call{Call: _e.mock.On("Resource")}
}

func (_c *Evaluator_Resource_Call) Run(run func()) *Evaluator_Resource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Evaluator_Resource_Call) Return(v config.PolicyResourceType) *Evaluator_Resource_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Evaluator_Resource_Call) RunAndReturn(run func() config.PolicyResourceType) *Evaluator_Resource_Call {
	_c.Call.Return(run)
	return _c
}
