// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/goto/raccoon/ingestionrule/action/eventregistry"
	mock "github.com/stretchr/testify/mock"
)

// NewEventChecker creates a new instance of EventChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventChecker {
	mock := &EventChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventChecker is an autogenerated mock type for the EventChecker type
type EventChecker struct {
	mock.Mock
}

type EventChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *EventChecker) EXPECT() *EventChecker_Expecter {
	return &EventChecker_Expecter{mock: &_m.Mock}
}

// BuildCacheKey provides a mock function for the type EventChecker
func (_mock *EventChecker) BuildCacheKey(publisher string, topic string, product string, eventName string) string {
	ret := _mock.Called(publisher, topic, product, eventName)

	if len(ret) == 0 {
		panic("no return value specified for BuildCacheKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = returnFunc(publisher, topic, product, eventName)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// EventChecker_BuildCacheKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildCacheKey'
type EventChecker_BuildCacheKey_Call struct {
	*mock.Call
}

// BuildCacheKey is a helper method to define mock.On call
//   - publisher string
//   - topic string
//   - product string
//   - eventName string
func (_e *EventChecker_Expecter) BuildCacheKey(publisher interface{}, topic interface{}, product interface{}, eventName interface{}) *EventChecker_BuildCacheKey_Call {
	return &EventChecker_BuildCacheKey_Call{Call: _e.mock.On("BuildCacheKey", publisher, topic, product, eventName)}
}

func (_c *EventChecker_BuildCacheKey_Call) Run(run func(publisher string, topic string, product string, eventName string)) *EventChecker_BuildCacheKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EventChecker_BuildCacheKey_Call) Return(s string) *EventChecker_BuildCacheKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *EventChecker_BuildCacheKey_Call) RunAndReturn(run func(publisher string, topic string, product string, eventName string) string) *EventChecker_BuildCacheKey_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type EventChecker
func (_mock *EventChecker) Close() {
	_mock.Called()
	return
}

// EventChecker_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type EventChecker_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *EventChecker_Expecter) Close() *EventChecker_Close_Call {
	return &EventChecker_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *EventChecker_Close_Call) Run(run func()) *EventChecker_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventChecker_Close_Call) Return() *EventChecker_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventChecker_Close_Call) RunAndReturn(run func()) *EventChecker_Close_Call {
	_c.Run(run)
	return _c
}

// GetEvents provides a mock function for the type EventChecker
func (_mock *EventChecker) GetEvents(key string) (eventregistry.EventStatus, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 eventregistry.EventStatus
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (eventregistry.EventStatus, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) eventregistry.EventStatus); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(eventregistry.EventStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// EventChecker_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type EventChecker_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - key string
func (_e *EventChecker_Expecter) GetEvents(key interface{}) *EventChecker_GetEvents_Call {
	return &EventChecker_GetEvents_Call{Call: _e.mock.On("GetEvents", key)}
}

func (_c *EventChecker_GetEvents_Call) Run(run func(key string)) *EventChecker_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EventChecker_GetEvents_Call) Return(eventStatus eventregistry.EventStatus, b bool) *EventChecker_GetEvents_Call {
	_c.Call.Return(eventStatus, b)
	return _c
}

func (_c *EventChecker_GetEvents_Call) RunAndReturn(run func(key string) (eventregistry.EventStatus, bool)) *EventChecker_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// HasSynced provides a mock function for the type EventChecker
func (_mock *EventChecker) HasSynced() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasSynced")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// EventChecker_HasSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasSynced'
type EventChecker_HasSynced_Call struct {
	*mock.Call
}

// HasSynced is a helper method to define mock.On call
func (_e *EventChecker_Expecter) HasSynced() *EventChecker_HasSynced_Call {
	return &EventChecker_HasSynced_Call{Call: _e.mock.On("HasSynced")}
}

func (_c *EventChecker_HasSynced_Call) Run(run func()) *EventChecker_HasSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventChecker_HasSynced_Call) Return(b bool) *EventChecker_HasSynced_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *EventChecker_HasSynced_Call) RunAndReturn(run func() bool) *EventChecker_HasSynced_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function for the type EventChecker
func (_mock *EventChecker) HealthCheck() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EventChecker_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type EventChecker_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
func (_e *EventChecker_Expecter) HealthCheck() *EventChecker_HealthCheck_Call {
	return &EventChecker_HealthCheck_Call{Call: _e.mock.On("HealthCheck")}
}

func (_c *EventChecker_HealthCheck_Call) Run(run func()) *EventChecker_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventChecker_HealthCheck_Call) Return(err error) *EventChecker_HealthCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EventChecker_HealthCheck_Call) RunAndReturn(run func() error) *EventChecker_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type EventChecker
func (_mock *EventChecker) Start() {
	_mock.Called()
	return
}

// EventChecker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type EventChecker_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *EventChecker_Expecter) Start() *EventChecker_Start_Call {
	return &EventChecker_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *EventChecker_Start_Call) Run(run func()) *EventChecker_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventChecker_Start_Call) Return() *EventChecker_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventChecker_Start_Call) RunAndReturn(run func()) *EventChecker_Start_Call {
	_c.Run(run)
	return _c
}
