// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewSchemaCache creates a new instance of SchemaCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchemaCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchemaCache {
	mock := &SchemaCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SchemaCache is an autogenerated mock type for the SchemaCache type
type SchemaCache struct {
	mock.Mock
}

type SchemaCache_Expecter struct {
	mock *mock.Mock
}

func (_m *SchemaCache) EXPECT() *SchemaCache_Expecter {
	return &SchemaCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type SchemaCache
func (_mock *SchemaCache) Get(topic string) (string, bool) {
	ret := _mock.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(topic)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(topic)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(topic)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// SchemaCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SchemaCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - topic string
func (_e *SchemaCache_Expecter) Get(topic interface{}) *SchemaCache_Get_Call {
	return &SchemaCache_Get_Call{Call: _e.mock.On("Get", topic)}
}

func (_c *SchemaCache_Get_Call) Run(run func(topic string)) *SchemaCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SchemaCache_Get_Call) Return(s string, b bool) *SchemaCache_Get_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *SchemaCache_Get_Call) RunAndReturn(run func(topic string) (string, bool)) *SchemaCache_Get_Call {
	_c.Call.Return(run)
	return _c
}
