// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// NewStencilClient creates a new instance of StencilClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStencilClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *StencilClient {
	mock := &StencilClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StencilClient is an autogenerated mock type for the StencilClient type
type StencilClient struct {
	mock.Mock
}

type StencilClient_Expecter struct {
	mock *mock.Mock
}

func (_m *StencilClient) EXPECT() *StencilClient_Expecter {
	return &StencilClient_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type StencilClient
func (_mock *StencilClient) Parse(className string, data []byte) (protoreflect.ProtoMessage, error) {
	ret := _mock.Called(className, data)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 protoreflect.ProtoMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) (protoreflect.ProtoMessage, error)); ok {
		return returnFunc(className, data)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) protoreflect.ProtoMessage); ok {
		r0 = returnFunc(className, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(protoreflect.ProtoMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(className, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StencilClient_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type StencilClient_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - className string
//   - data []byte
func (_e *StencilClient_Expecter) Parse(className interface{}, data interface{}) *StencilClient_Parse_Call {
	return &StencilClient_Parse_Call{Call: _e.mock.On("Parse", className, data)}
}

func (_c *StencilClient_Parse_Call) Run(run func(className string, data []byte)) *StencilClient_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StencilClient_Parse_Call) Return(protoMessage protoreflect.ProtoMessage, err error) *StencilClient_Parse_Call {
	_c.Call.Return(protoMessage, err)
	return _c
}

func (_c *StencilClient_Parse_Call) RunAndReturn(run func(className string, data []byte) (protoreflect.ProtoMessage, error)) *StencilClient_Parse_Call {
	_c.Call.Return(run)
	return _c
}
