// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"encoding/json"

	"github.com/goto/raccoon/ingestionrule/schemaregistry/deserialization/http"
	mock "github.com/stretchr/testify/mock"
)

// NewHTTPClient creates a new instance of HTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPClient {
	mock := &HTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HTTPClient is an autogenerated mock type for the HTTPClient type
type HTTPClient struct {
	mock.Mock
}

type HTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *HTTPClient) EXPECT() *HTTPClient_Expecter {
	return &HTTPClient_Expecter{mock: &_m.Mock}
}

// DoRequest provides a mock function for the type HTTPClient
func (_mock *HTTPClient) DoRequest(ctx context.Context, request http.Request) (json.RawMessage, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for DoRequest")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, http.Request) (json.RawMessage, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, http.Request) json.RawMessage); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, http.Request) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HTTPClient_DoRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoRequest'
type HTTPClient_DoRequest_Call struct {
	*mock.Call
}

// DoRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - request http.Request
func (_e *HTTPClient_Expecter) DoRequest(ctx interface{}, request interface{}) *HTTPClient_DoRequest_Call {
	return &HTTPClient_DoRequest_Call{Call: _e.mock.On("DoRequest", ctx, request)}
}

func (_c *HTTPClient_DoRequest_Call) Run(run func(ctx context.Context, request http.Request)) *HTTPClient_DoRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 http.Request
		if args[1] != nil {
			arg1 = args[1].(http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HTTPClient_DoRequest_Call) Return(rawMessage json.RawMessage, err error) *HTTPClient_DoRequest_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *HTTPClient_DoRequest_Call) RunAndReturn(run func(ctx context.Context, request http.Request) (json.RawMessage, error)) *HTTPClient_DoRequest_Call {
	_c.Call.Return(run)
	return _c
}
