// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewSchemaRegistryCache creates a new instance of SchemaRegistryCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchemaRegistryCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchemaRegistryCache {
	mock := &SchemaRegistryCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SchemaRegistryCache is an autogenerated mock type for the SchemaRegistryCache type
type SchemaRegistryCache struct {
	mock.Mock
}

type SchemaRegistryCache_Expecter struct {
	mock *mock.Mock
}

func (_m *SchemaRegistryCache) EXPECT() *SchemaRegistryCache_Expecter {
	return &SchemaRegistryCache_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type SchemaRegistryCache
func (_mock *SchemaRegistryCache) Close() {
	_mock.Called()
	return
}

// SchemaRegistryCache_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type SchemaRegistryCache_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *SchemaRegistryCache_Expecter) Close() *SchemaRegistryCache_Close_Call {
	return &SchemaRegistryCache_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *SchemaRegistryCache_Close_Call) Run(run func()) *SchemaRegistryCache_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SchemaRegistryCache_Close_Call) Return() *SchemaRegistryCache_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *SchemaRegistryCache_Close_Call) RunAndReturn(run func()) *SchemaRegistryCache_Close_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type SchemaRegistryCache
func (_mock *SchemaRegistryCache) Get(topic string) (string, bool) {
	ret := _mock.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(topic)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(topic)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(topic)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// SchemaRegistryCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SchemaRegistryCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - topic string
func (_e *SchemaRegistryCache_Expecter) Get(topic interface{}) *SchemaRegistryCache_Get_Call {
	return &SchemaRegistryCache_Get_Call{Call: _e.mock.On("Get", topic)}
}

func (_c *SchemaRegistryCache_Get_Call) Run(run func(topic string)) *SchemaRegistryCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SchemaRegistryCache_Get_Call) Return(s string, b bool) *SchemaRegistryCache_Get_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *SchemaRegistryCache_Get_Call) RunAndReturn(run func(topic string) (string, bool)) *SchemaRegistryCache_Get_Call {
	_c.Call.Return(run)
	return _c
}
