name: Raccoon Test & Build

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.23'
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Project
        run: make setup
      - name: Invoking go test
        run: make test
      - name: Invoking go bench test
        run: make test-bench
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.23'
      - uses: actions/checkout@v2
      - name: Build
        run: make all
